certspltr packaging: new go-install behavior for g.18+

diff --git a/packages/rootfs-certsplitter/packaging b/packages/rootfs-certsplitter/packaging
--- a/packages/rootfs-certsplitter/packaging
+++ b/packages/rootfs-certsplitter/packaging
@@ -5,10 +5,18 @@ source /var/vcap/packages/golang-1.19-linux/bosh/compile.env
 mkdir -p ${BOSH_INSTALL_TARGET}/src
 cp -a . ${BOSH_INSTALL_TARGET}/src
 export GOPATH=$BOSH_INSTALL_TARGET
+export GOBIN=$GOPATH/bin
 
 export GOROOT=$(readlink -nf /var/vcap/packages/golang-1.19-linux)
 export PATH=$GOROOT/bin:$PATH
 
-go install code.cloudfoundry.org/certsplitter/cmd/certsplitter
+pushd code.cloudfoundry.org/certsplitter
+  go install -buildvcs=false code.cloudfoundry.org/certsplitter/cmd/certsplitter
+popd
+
+if [ ! -f "/var/vcap/packages/rootfs-certsplitter-cflinuxfs3/bin/certsplitter" ]; then
+  echo "certsplitter install failed"
+  exit 1
+fi
 
 rm -rf ${BOSH_INSTALL_TARGET}/src ${BOSH_INSTALL_TARGET}/pkg
